language: minimal
jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - '10'
      cache: yarn
      before_install:
        - echo "Skipping before install"
      script:
        - yarn danger ci
      if: type = pull_request
    - stage: deploy
      script:
        - curl -f -XPOST -H "$DX_HEADER" $IMPORT_URL_STAGING -d "branch=$TRAVIS_PULL_REQUEST_BRANCH"
      if: |
        branch = master AND \
        type = pull_request
    - stage: deploy
      script:
        - curl -f -XPOST -H "$DX_HEADER" $IMPORT_URL
      if: |
        branch = master AND \
        type = push
env:
  global:
    secure: AXaLSba0kjiC4tvu0buyppkEhTNLseFFFvrGw+2W+ZELL6Aqkvpda+gn0jUA3RoYbgwUW1kE/R5/jzgOBZoVEFzg8Tgl+cMCqEZfj4sqb65vP1vZfOA8UMZ+dqsdMHo7liIKti3g+hMgO3RGrP2KT83otZzJMelMbmVSE9b7laxXiytLwstHputYi89XESy+RXgO965x9ofmER04kQIKwqnSEz9Bp+QOldyY9yjyKnt43nnl7RCuCL/WazCktGiGex7zBFqICORhnQ51x7V4sqOYKis9FUZmk9jxUlfT4IaoJP9DYGQ2VWQq5OK31sZ0OcfIfPdPV/+klr65nd/U0U8qv3kjD0x+ZrfsrrvXpu/lJiq4MRYqwaATCqZk+1tpRMkrtSFdsj1FL6qm0SRfN6SUeQxnqeLvGu5GAj+axx7ziY4F83YeX570mDufoEYGyNcld1MmHfFrUi1zb6I2bF1nh232OWt4/2vkdNVMlti0q7yj78CJ5DBpiTfh3Dzton6MVqqVgbmWcwghohja5O+Qq6sBtvxB0gNYAsdJJvfLOdBQUwmonDDVyiJO84gy5WYZNkkiGFHBF2eHIAXsyVMtAXWUGfmVy1e9w+bk2WdM7Fnxr4HedWwF4yyJHrKpqJ/Q3YZJGTINLp42QjVqmH6cJkrLwRWvl6ftN/L6L2k=
