language: minimal
jobs:
  include:
  - stage: test
    language: node_js
    node_js:
    - '10'
    cache: yarn
    before_install:
    - echo "Skipping before install"
    script:
    - yarn danger ci
    if: type = pull_request
  - stage: deploy
    script:
    - curl -f -XPOST -H "$AUTH_HEADER" -H "$DX_HEADER" $IMPORT_URL_STAGING -d "branch=$TRAVIS_PULL_REQUEST_BRANCH"
    if: |
      branch = master AND \
      type = pull_request
  - stage: deploy
    script:
    - curl -f -XPOST -H "$AUTH_HEADER" -H "$DX_HEADER" $IMPORT_URL
    if: |
      branch = master AND \
      type = push
