language: minimal
jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - '10'
      cache: yarn
      before_install:
        - echo "Skipping before install"
      script:
        - yarn danger ci
      if: type = pull_request
    - stage: deploy
      script:
        - curl -f -XPOST -H "$DX_HEADER" $IMPORT_URL_STAGING -d "branch=$TRAVIS_PULL_REQUEST_BRANCH"
      if: |
        branch = master AND \
        type = pull_request
    - stage: deploy
      script:
        - curl -f -XPOST -H "$DX_HEADER" $IMPORT_URL
      if: |
        branch = master AND \
        type = push
env:
  global:
    - secure: O6ysXbWMsdhqw7BLUnZmC/wrnT5fkBXshdZpUXmErTqz41kRi7wi2blJ+mK3O4QaGXIworcrPO1Ugo1H8dKqtq7Ru/TK14wUBQI+36bzJP0P0+3cWM1J/+XkvvQ/ShyRP1M+WGkzqVDIb71QzQ+D+QKrwkScWE78vYyvK9lnfRR6NLSveBy5p2bso1hnm5091Zq8GUqWxUKAybChFk7SY1nz1M2gTbH4UiCSEjRuKM7lb4537OQuMhvHWZGe6To1yRZ10eQEV+Ixf6WKPZXaPt2wNOdsnWO2956t6FVz8Ua+RzESE2Irb5oAaPec+noZqJX8wMP5VNuZt171UL3sMbEld8gKg83xR9iGyyB+hXbW4YWZle4oi/VR6XF0O6D3Ym7R0FhriYh2LDNPNrPEHXF5WZDOcrvVTXdnZ+SGa0QAbSc1y2AhrL1Yl5bzwmFBkzIwI1g/vQ2xwBs/rEx3upd8D3aITJX3n+CoI9SEAaBsNVk5vSFTHkGRuEOd9xCd20rfK4hkWh14eiIWVYZ/By1dOyXU0MQAcFDKJcirLY4u4M+HL5PytO0upv7y8iGPUINdOCaQ2Ha+BnDFsxLDYpYeKUNcUHooCBdrxk4zRw9wazGQ6IQ4keKI6QlRejAEfGVJFnwOdnok8DN40GbIp9WuVSQnx12ctRUEl3Fh4Yw= # DANGER_GITHUB_API_TOKEN
